lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "click"
version = "8.1.7"

[[packages.wheels]]
name = "click-8.1.7-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "ae74fb96c20a0277a1d615f1e4d73c8414f5a98db8b799a7931d1582f3390c28"

[[packages]]
name = "dep-1"

[packages.vcs]
type = "git"
url = "https://github.com/rabkins/dep-1"
requested-revision = "v0.0.5"
commit-id = "6e7fc03054e3c68ab213c6c24cb618e31e00351c"

[[packages]]
name = "dep-2"

[packages.vcs]
type = "git"
url = "https://github.com/rabkins/dep-2"
requested-revision = "v0.0.4"
commit-id = "e0a65594b94d3707816fc8284c8661ca8f461c4d"

[[packages]]
name = "my-project"

[packages.directory]
path = "."
